#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurboPezzi
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TurboPezzi")]
	public partial class sqlDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertVENDITA(VENDITA instance);
    partial void UpdateVENDITA(VENDITA instance);
    partial void DeleteVENDITA(VENDITA instance);
    partial void InsertCLIENTE(CLIENTE instance);
    partial void UpdateCLIENTE(CLIENTE instance);
    partial void DeleteCLIENTE(CLIENTE instance);
    partial void Insertcomposizione_acquisto(composizione_acquisto instance);
    partial void Updatecomposizione_acquisto(composizione_acquisto instance);
    partial void Deletecomposizione_acquisto(composizione_acquisto instance);
    partial void InsertCONTRATTO(CONTRATTO instance);
    partial void UpdateCONTRATTO(CONTRATTO instance);
    partial void DeleteCONTRATTO(CONTRATTO instance);
    partial void InsertDETTAGLIO_ORDINE(DETTAGLIO_ORDINE instance);
    partial void UpdateDETTAGLIO_ORDINE(DETTAGLIO_ORDINE instance);
    partial void DeleteDETTAGLIO_ORDINE(DETTAGLIO_ORDINE instance);
    partial void InsertDIPENDENTE(DIPENDENTE instance);
    partial void UpdateDIPENDENTE(DIPENDENTE instance);
    partial void DeleteDIPENDENTE(DIPENDENTE instance);
    partial void InsertFATTURA_DI_ACQUISTO(FATTURA_DI_ACQUISTO instance);
    partial void UpdateFATTURA_DI_ACQUISTO(FATTURA_DI_ACQUISTO instance);
    partial void DeleteFATTURA_DI_ACQUISTO(FATTURA_DI_ACQUISTO instance);
    partial void InsertFATTURA_DI_VENDITA(FATTURA_DI_VENDITA instance);
    partial void UpdateFATTURA_DI_VENDITA(FATTURA_DI_VENDITA instance);
    partial void DeleteFATTURA_DI_VENDITA(FATTURA_DI_VENDITA instance);
    partial void InsertFORNITORE(FORNITORE instance);
    partial void UpdateFORNITORE(FORNITORE instance);
    partial void DeleteFORNITORE(FORNITORE instance);
    partial void InsertMAGAZZINO(MAGAZZINO instance);
    partial void UpdateMAGAZZINO(MAGAZZINO instance);
    partial void DeleteMAGAZZINO(MAGAZZINO instance);
    partial void InsertMOTO(MOTO instance);
    partial void UpdateMOTO(MOTO instance);
    partial void DeleteMOTO(MOTO instance);
    partial void InsertRICAMBIO(RICAMBIO instance);
    partial void UpdateRICAMBIO(RICAMBIO instance);
    partial void DeleteRICAMBIO(RICAMBIO instance);
    partial void InsertRIGENERAZIONE(RIGENERAZIONE instance);
    partial void UpdateRIGENERAZIONE(RIGENERAZIONE instance);
    partial void DeleteRIGENERAZIONE(RIGENERAZIONE instance);
    partial void InsertTITOLARE(TITOLARE instance);
    partial void UpdateTITOLARE(TITOLARE instance);
    partial void DeleteTITOLARE(TITOLARE instance);
    #endregion
		
		public sqlDataContext() : 
				base(global::TurboPezzi.Properties.Settings.Default.TurboPezziConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public sqlDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public sqlDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public sqlDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public sqlDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<VENDITA> VENDITAs
		{
			get
			{
				return this.GetTable<VENDITA>();
			}
		}
		
		public System.Data.Linq.Table<CLIENTE> CLIENTEs
		{
			get
			{
				return this.GetTable<CLIENTE>();
			}
		}
		
		public System.Data.Linq.Table<composizione_acquisto> composizione_acquistos
		{
			get
			{
				return this.GetTable<composizione_acquisto>();
			}
		}
		
		public System.Data.Linq.Table<CONTRATTO> CONTRATTOs
		{
			get
			{
				return this.GetTable<CONTRATTO>();
			}
		}
		
		public System.Data.Linq.Table<DETTAGLIO_ORDINE> DETTAGLIO_ORDINEs
		{
			get
			{
				return this.GetTable<DETTAGLIO_ORDINE>();
			}
		}
		
		public System.Data.Linq.Table<DIPENDENTE> DIPENDENTEs
		{
			get
			{
				return this.GetTable<DIPENDENTE>();
			}
		}
		
		public System.Data.Linq.Table<FATTURA_DI_ACQUISTO> FATTURA_DI_ACQUISTOs
		{
			get
			{
				return this.GetTable<FATTURA_DI_ACQUISTO>();
			}
		}
		
		public System.Data.Linq.Table<FATTURA_DI_VENDITA> FATTURA_DI_VENDITAs
		{
			get
			{
				return this.GetTable<FATTURA_DI_VENDITA>();
			}
		}
		
		public System.Data.Linq.Table<FORNITORE> FORNITOREs
		{
			get
			{
				return this.GetTable<FORNITORE>();
			}
		}
		
		public System.Data.Linq.Table<MAGAZZINO> MAGAZZINOs
		{
			get
			{
				return this.GetTable<MAGAZZINO>();
			}
		}
		
		public System.Data.Linq.Table<MOTO> MOTOs
		{
			get
			{
				return this.GetTable<MOTO>();
			}
		}
		
		public System.Data.Linq.Table<RICAMBIO> RICAMBIOs
		{
			get
			{
				return this.GetTable<RICAMBIO>();
			}
		}
		
		public System.Data.Linq.Table<RIGENERAZIONE> RIGENERAZIONEs
		{
			get
			{
				return this.GetTable<RIGENERAZIONE>();
			}
		}
		
		public System.Data.Linq.Table<TITOLARE> TITOLAREs
		{
			get
			{
				return this.GetTable<TITOLARE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VENDITA")]
	public partial class VENDITA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _CodiceImpiegato;
		
		private decimal _CodiceVendita;
		
		private string _Descrizione;
		
		private decimal _CodiceFatturaV;
		
		private EntitySet<DETTAGLIO_ORDINE> _DETTAGLIO_ORDINEs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodiceImpiegatoChanging(decimal value);
    partial void OnCodiceImpiegatoChanged();
    partial void OnCodiceVenditaChanging(decimal value);
    partial void OnCodiceVenditaChanged();
    partial void OnDescrizioneChanging(string value);
    partial void OnDescrizioneChanged();
    partial void OnCodiceFatturaVChanging(decimal value);
    partial void OnCodiceFatturaVChanged();
    #endregion
		
		public VENDITA()
		{
			this._DETTAGLIO_ORDINEs = new EntitySet<DETTAGLIO_ORDINE>(new Action<DETTAGLIO_ORDINE>(this.attach_DETTAGLIO_ORDINEs), new Action<DETTAGLIO_ORDINE>(this.detach_DETTAGLIO_ORDINEs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceImpiegato", DbType="Decimal(3,0) NOT NULL", IsPrimaryKey=true)]
		public decimal CodiceImpiegato
		{
			get
			{
				return this._CodiceImpiegato;
			}
			set
			{
				if ((this._CodiceImpiegato != value))
				{
					this.OnCodiceImpiegatoChanging(value);
					this.SendPropertyChanging();
					this._CodiceImpiegato = value;
					this.SendPropertyChanged("CodiceImpiegato");
					this.OnCodiceImpiegatoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceVendita", DbType="Decimal(5,0) NOT NULL", IsPrimaryKey=true)]
		public decimal CodiceVendita
		{
			get
			{
				return this._CodiceVendita;
			}
			set
			{
				if ((this._CodiceVendita != value))
				{
					this.OnCodiceVenditaChanging(value);
					this.SendPropertyChanging();
					this._CodiceVendita = value;
					this.SendPropertyChanged("CodiceVendita");
					this.OnCodiceVenditaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descrizione", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string Descrizione
		{
			get
			{
				return this._Descrizione;
			}
			set
			{
				if ((this._Descrizione != value))
				{
					this.OnDescrizioneChanging(value);
					this.SendPropertyChanging();
					this._Descrizione = value;
					this.SendPropertyChanged("Descrizione");
					this.OnDescrizioneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceFatturaV", DbType="Decimal(6,0) NOT NULL")]
		public decimal CodiceFatturaV
		{
			get
			{
				return this._CodiceFatturaV;
			}
			set
			{
				if ((this._CodiceFatturaV != value))
				{
					this.OnCodiceFatturaVChanging(value);
					this.SendPropertyChanging();
					this._CodiceFatturaV = value;
					this.SendPropertyChanged("CodiceFatturaV");
					this.OnCodiceFatturaVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VENDITA_DETTAGLIO_ORDINE", Storage="_DETTAGLIO_ORDINEs", ThisKey="CodiceImpiegato,CodiceVendita", OtherKey="CodiceImpiegato,CodiceVendita")]
		public EntitySet<DETTAGLIO_ORDINE> DETTAGLIO_ORDINEs
		{
			get
			{
				return this._DETTAGLIO_ORDINEs;
			}
			set
			{
				this._DETTAGLIO_ORDINEs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DETTAGLIO_ORDINEs(DETTAGLIO_ORDINE entity)
		{
			this.SendPropertyChanging();
			entity.VENDITA = this;
		}
		
		private void detach_DETTAGLIO_ORDINEs(DETTAGLIO_ORDINE entity)
		{
			this.SendPropertyChanging();
			entity.VENDITA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CLIENTE")]
	public partial class CLIENTE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CF;
		
		private string _Nome;
		
		private string _Cognome;
		
		private System.Nullable<decimal> _Telefono;
		
		private string _Mail;
		
		private System.DateTime _Data_di_nascita;
		
		private EntitySet<FATTURA_DI_VENDITA> _FATTURA_DI_VENDITAs;
		
		private EntitySet<MOTO> _MOTOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCFChanging(string value);
    partial void OnCFChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnCognomeChanging(string value);
    partial void OnCognomeChanged();
    partial void OnTelefonoChanging(System.Nullable<decimal> value);
    partial void OnTelefonoChanged();
    partial void OnMailChanging(string value);
    partial void OnMailChanged();
    partial void OnData_di_nascitaChanging(System.DateTime value);
    partial void OnData_di_nascitaChanged();
    #endregion
		
		public CLIENTE()
		{
			this._FATTURA_DI_VENDITAs = new EntitySet<FATTURA_DI_VENDITA>(new Action<FATTURA_DI_VENDITA>(this.attach_FATTURA_DI_VENDITAs), new Action<FATTURA_DI_VENDITA>(this.detach_FATTURA_DI_VENDITAs));
			this._MOTOs = new EntitySet<MOTO>(new Action<MOTO>(this.attach_MOTOs), new Action<MOTO>(this.detach_MOTOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CF", DbType="Char(25) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CF
		{
			get
			{
				return this._CF;
			}
			set
			{
				if ((this._CF != value))
				{
					this.OnCFChanging(value);
					this.SendPropertyChanging();
					this._CF = value;
					this.SendPropertyChanged("CF");
					this.OnCFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cognome", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string Cognome
		{
			get
			{
				return this._Cognome;
			}
			set
			{
				if ((this._Cognome != value))
				{
					this.OnCognomeChanging(value);
					this.SendPropertyChanging();
					this._Cognome = value;
					this.SendPropertyChanged("Cognome");
					this.OnCognomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail", DbType="Char(30)")]
		public string Mail
		{
			get
			{
				return this._Mail;
			}
			set
			{
				if ((this._Mail != value))
				{
					this.OnMailChanging(value);
					this.SendPropertyChanging();
					this._Mail = value;
					this.SendPropertyChanged("Mail");
					this.OnMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Data di nascita]", Storage="_Data_di_nascita", DbType="Date NOT NULL")]
		public System.DateTime Data_di_nascita
		{
			get
			{
				return this._Data_di_nascita;
			}
			set
			{
				if ((this._Data_di_nascita != value))
				{
					this.OnData_di_nascitaChanging(value);
					this.SendPropertyChanging();
					this._Data_di_nascita = value;
					this.SendPropertyChanged("Data_di_nascita");
					this.OnData_di_nascitaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLIENTE_FATTURA_DI_VENDITA", Storage="_FATTURA_DI_VENDITAs", ThisKey="CF", OtherKey="CF")]
		public EntitySet<FATTURA_DI_VENDITA> FATTURA_DI_VENDITAs
		{
			get
			{
				return this._FATTURA_DI_VENDITAs;
			}
			set
			{
				this._FATTURA_DI_VENDITAs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLIENTE_MOTO", Storage="_MOTOs", ThisKey="CF", OtherKey="CF")]
		public EntitySet<MOTO> MOTOs
		{
			get
			{
				return this._MOTOs;
			}
			set
			{
				this._MOTOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_FATTURA_DI_VENDITAs(FATTURA_DI_VENDITA entity)
		{
			this.SendPropertyChanging();
			entity.CLIENTE = this;
		}
		
		private void detach_FATTURA_DI_VENDITAs(FATTURA_DI_VENDITA entity)
		{
			this.SendPropertyChanging();
			entity.CLIENTE = null;
		}
		
		private void attach_MOTOs(MOTO entity)
		{
			this.SendPropertyChanging();
			entity.CLIENTE = this;
		}
		
		private void detach_MOTOs(MOTO entity)
		{
			this.SendPropertyChanging();
			entity.CLIENTE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.composizione_acquisto")]
	public partial class composizione_acquisto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _CodiceRicambio;
		
		private decimal _CodiceFatturaA;
		
		private decimal _Quantità;
		
		private decimal _Prezzo_unitario;
		
		private EntityRef<FATTURA_DI_ACQUISTO> _FATTURA_DI_ACQUISTO;
		
		private EntityRef<RICAMBIO> _RICAMBIO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodiceRicambioChanging(decimal value);
    partial void OnCodiceRicambioChanged();
    partial void OnCodiceFatturaAChanging(decimal value);
    partial void OnCodiceFatturaAChanged();
    partial void OnQuantitàChanging(decimal value);
    partial void OnQuantitàChanged();
    partial void OnPrezzo_unitarioChanging(decimal value);
    partial void OnPrezzo_unitarioChanged();
    #endregion
		
		public composizione_acquisto()
		{
			this._FATTURA_DI_ACQUISTO = default(EntityRef<FATTURA_DI_ACQUISTO>);
			this._RICAMBIO = default(EntityRef<RICAMBIO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceRicambio", DbType="Decimal(6,0) NOT NULL", IsPrimaryKey=true)]
		public decimal CodiceRicambio
		{
			get
			{
				return this._CodiceRicambio;
			}
			set
			{
				if ((this._CodiceRicambio != value))
				{
					if (this._RICAMBIO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodiceRicambioChanging(value);
					this.SendPropertyChanging();
					this._CodiceRicambio = value;
					this.SendPropertyChanged("CodiceRicambio");
					this.OnCodiceRicambioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceFatturaA", DbType="Decimal(6,0) NOT NULL", IsPrimaryKey=true)]
		public decimal CodiceFatturaA
		{
			get
			{
				return this._CodiceFatturaA;
			}
			set
			{
				if ((this._CodiceFatturaA != value))
				{
					if (this._FATTURA_DI_ACQUISTO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodiceFatturaAChanging(value);
					this.SendPropertyChanging();
					this._CodiceFatturaA = value;
					this.SendPropertyChanged("CodiceFatturaA");
					this.OnCodiceFatturaAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantità", DbType="Decimal(3,0) NOT NULL")]
		public decimal Quantità
		{
			get
			{
				return this._Quantità;
			}
			set
			{
				if ((this._Quantità != value))
				{
					this.OnQuantitàChanging(value);
					this.SendPropertyChanging();
					this._Quantità = value;
					this.SendPropertyChanged("Quantità");
					this.OnQuantitàChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Prezzo unitario]", Storage="_Prezzo_unitario", DbType="Decimal(5,0) NOT NULL")]
		public decimal Prezzo_unitario
		{
			get
			{
				return this._Prezzo_unitario;
			}
			set
			{
				if ((this._Prezzo_unitario != value))
				{
					this.OnPrezzo_unitarioChanging(value);
					this.SendPropertyChanging();
					this._Prezzo_unitario = value;
					this.SendPropertyChanged("Prezzo_unitario");
					this.OnPrezzo_unitarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FATTURA_DI_ACQUISTO_composizione_acquisto", Storage="_FATTURA_DI_ACQUISTO", ThisKey="CodiceFatturaA", OtherKey="CodiceFatturaA", IsForeignKey=true)]
		public FATTURA_DI_ACQUISTO FATTURA_DI_ACQUISTO
		{
			get
			{
				return this._FATTURA_DI_ACQUISTO.Entity;
			}
			set
			{
				FATTURA_DI_ACQUISTO previousValue = this._FATTURA_DI_ACQUISTO.Entity;
				if (((previousValue != value) 
							|| (this._FATTURA_DI_ACQUISTO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._FATTURA_DI_ACQUISTO.Entity = null;
						previousValue.composizione_acquistos.Remove(this);
					}
					this._FATTURA_DI_ACQUISTO.Entity = value;
					if ((value != null))
					{
						value.composizione_acquistos.Add(this);
						this._CodiceFatturaA = value.CodiceFatturaA;
					}
					else
					{
						this._CodiceFatturaA = default(decimal);
					}
					this.SendPropertyChanged("FATTURA_DI_ACQUISTO");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RICAMBIO_composizione_acquisto", Storage="_RICAMBIO", ThisKey="CodiceRicambio", OtherKey="CodiceRicambio", IsForeignKey=true)]
		public RICAMBIO RICAMBIO
		{
			get
			{
				return this._RICAMBIO.Entity;
			}
			set
			{
				RICAMBIO previousValue = this._RICAMBIO.Entity;
				if (((previousValue != value) 
							|| (this._RICAMBIO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._RICAMBIO.Entity = null;
						previousValue.composizione_acquistos.Remove(this);
					}
					this._RICAMBIO.Entity = value;
					if ((value != null))
					{
						value.composizione_acquistos.Add(this);
						this._CodiceRicambio = value.CodiceRicambio;
					}
					else
					{
						this._CodiceRicambio = default(decimal);
					}
					this.SendPropertyChanged("RICAMBIO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CONTRATTO")]
	public partial class CONTRATTO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _CodiceImpiegato;
		
		private decimal _CodiceContratto;
		
		private System.DateTime _Data_assunzione;
		
		private System.Nullable<System.DateTime> _Data_Termine;
		
		private string _Tipologia;
		
		private decimal _Stipendio;
		
		private decimal _Codicetitolare;
		
		private EntityRef<DIPENDENTE> _DIPENDENTE;
		
		private EntityRef<TITOLARE> _TITOLARE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodiceImpiegatoChanging(decimal value);
    partial void OnCodiceImpiegatoChanged();
    partial void OnCodiceContrattoChanging(decimal value);
    partial void OnCodiceContrattoChanged();
    partial void OnData_assunzioneChanging(System.DateTime value);
    partial void OnData_assunzioneChanged();
    partial void OnData_TermineChanging(System.Nullable<System.DateTime> value);
    partial void OnData_TermineChanged();
    partial void OnTipologiaChanging(string value);
    partial void OnTipologiaChanged();
    partial void OnStipendioChanging(decimal value);
    partial void OnStipendioChanged();
    partial void OnCodicetitolareChanging(decimal value);
    partial void OnCodicetitolareChanged();
    #endregion
		
		public CONTRATTO()
		{
			this._DIPENDENTE = default(EntityRef<DIPENDENTE>);
			this._TITOLARE = default(EntityRef<TITOLARE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceImpiegato", DbType="Decimal(3,0) NOT NULL", IsPrimaryKey=true)]
		public decimal CodiceImpiegato
		{
			get
			{
				return this._CodiceImpiegato;
			}
			set
			{
				if ((this._CodiceImpiegato != value))
				{
					if (this._DIPENDENTE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodiceImpiegatoChanging(value);
					this.SendPropertyChanging();
					this._CodiceImpiegato = value;
					this.SendPropertyChanged("CodiceImpiegato");
					this.OnCodiceImpiegatoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceContratto", DbType="Decimal(3,0) NOT NULL", IsPrimaryKey=true)]
		public decimal CodiceContratto
		{
			get
			{
				return this._CodiceContratto;
			}
			set
			{
				if ((this._CodiceContratto != value))
				{
					this.OnCodiceContrattoChanging(value);
					this.SendPropertyChanging();
					this._CodiceContratto = value;
					this.SendPropertyChanged("CodiceContratto");
					this.OnCodiceContrattoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Data assunzione]", Storage="_Data_assunzione", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime Data_assunzione
		{
			get
			{
				return this._Data_assunzione;
			}
			set
			{
				if ((this._Data_assunzione != value))
				{
					this.OnData_assunzioneChanging(value);
					this.SendPropertyChanging();
					this._Data_assunzione = value;
					this.SendPropertyChanged("Data_assunzione");
					this.OnData_assunzioneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Data Termine]", Storage="_Data_Termine", DbType="Date")]
		public System.Nullable<System.DateTime> Data_Termine
		{
			get
			{
				return this._Data_Termine;
			}
			set
			{
				if ((this._Data_Termine != value))
				{
					this.OnData_TermineChanging(value);
					this.SendPropertyChanging();
					this._Data_Termine = value;
					this.SendPropertyChanged("Data_Termine");
					this.OnData_TermineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipologia", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string Tipologia
		{
			get
			{
				return this._Tipologia;
			}
			set
			{
				if ((this._Tipologia != value))
				{
					this.OnTipologiaChanging(value);
					this.SendPropertyChanging();
					this._Tipologia = value;
					this.SendPropertyChanged("Tipologia");
					this.OnTipologiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stipendio", DbType="Decimal(4,0) NOT NULL")]
		public decimal Stipendio
		{
			get
			{
				return this._Stipendio;
			}
			set
			{
				if ((this._Stipendio != value))
				{
					this.OnStipendioChanging(value);
					this.SendPropertyChanging();
					this._Stipendio = value;
					this.SendPropertyChanged("Stipendio");
					this.OnStipendioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codicetitolare", DbType="Decimal(2,0) NOT NULL")]
		public decimal Codicetitolare
		{
			get
			{
				return this._Codicetitolare;
			}
			set
			{
				if ((this._Codicetitolare != value))
				{
					if (this._TITOLARE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodicetitolareChanging(value);
					this.SendPropertyChanging();
					this._Codicetitolare = value;
					this.SendPropertyChanged("Codicetitolare");
					this.OnCodicetitolareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DIPENDENTE_CONTRATTO", Storage="_DIPENDENTE", ThisKey="CodiceImpiegato", OtherKey="CodiceImpiegato", IsForeignKey=true)]
		public DIPENDENTE DIPENDENTE
		{
			get
			{
				return this._DIPENDENTE.Entity;
			}
			set
			{
				DIPENDENTE previousValue = this._DIPENDENTE.Entity;
				if (((previousValue != value) 
							|| (this._DIPENDENTE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DIPENDENTE.Entity = null;
						previousValue.CONTRATTOs.Remove(this);
					}
					this._DIPENDENTE.Entity = value;
					if ((value != null))
					{
						value.CONTRATTOs.Add(this);
						this._CodiceImpiegato = value.CodiceImpiegato;
					}
					else
					{
						this._CodiceImpiegato = default(decimal);
					}
					this.SendPropertyChanged("DIPENDENTE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TITOLARE_CONTRATTO", Storage="_TITOLARE", ThisKey="Codicetitolare", OtherKey="Codicetitolare", IsForeignKey=true)]
		public TITOLARE TITOLARE
		{
			get
			{
				return this._TITOLARE.Entity;
			}
			set
			{
				TITOLARE previousValue = this._TITOLARE.Entity;
				if (((previousValue != value) 
							|| (this._TITOLARE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TITOLARE.Entity = null;
						previousValue.CONTRATTOs.Remove(this);
					}
					this._TITOLARE.Entity = value;
					if ((value != null))
					{
						value.CONTRATTOs.Add(this);
						this._Codicetitolare = value.Codicetitolare;
					}
					else
					{
						this._Codicetitolare = default(decimal);
					}
					this.SendPropertyChanged("TITOLARE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[DETTAGLIO ORDINE]")]
	public partial class DETTAGLIO_ORDINE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _CodiceRicambio;
		
		private decimal _Numero_ordine;
		
		private decimal _CodiceImpiegato;
		
		private decimal _CodiceVendita;
		
		private decimal _Quantità;
		
		private decimal _Prezzo_unitario;
		
		private EntityRef<VENDITA> _VENDITA;
		
		private EntityRef<RICAMBIO> _RICAMBIO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodiceRicambioChanging(decimal value);
    partial void OnCodiceRicambioChanged();
    partial void OnNumero_ordineChanging(decimal value);
    partial void OnNumero_ordineChanged();
    partial void OnCodiceImpiegatoChanging(decimal value);
    partial void OnCodiceImpiegatoChanged();
    partial void OnCodiceVenditaChanging(decimal value);
    partial void OnCodiceVenditaChanged();
    partial void OnQuantitàChanging(decimal value);
    partial void OnQuantitàChanged();
    partial void OnPrezzo_unitarioChanging(decimal value);
    partial void OnPrezzo_unitarioChanged();
    #endregion
		
		public DETTAGLIO_ORDINE()
		{
			this._VENDITA = default(EntityRef<VENDITA>);
			this._RICAMBIO = default(EntityRef<RICAMBIO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceRicambio", DbType="Decimal(6,0) NOT NULL", IsPrimaryKey=true)]
		public decimal CodiceRicambio
		{
			get
			{
				return this._CodiceRicambio;
			}
			set
			{
				if ((this._CodiceRicambio != value))
				{
					if (this._RICAMBIO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodiceRicambioChanging(value);
					this.SendPropertyChanging();
					this._CodiceRicambio = value;
					this.SendPropertyChanged("CodiceRicambio");
					this.OnCodiceRicambioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Numero ordine]", Storage="_Numero_ordine", DbType="Decimal(6,0) NOT NULL", IsPrimaryKey=true)]
		public decimal Numero_ordine
		{
			get
			{
				return this._Numero_ordine;
			}
			set
			{
				if ((this._Numero_ordine != value))
				{
					this.OnNumero_ordineChanging(value);
					this.SendPropertyChanging();
					this._Numero_ordine = value;
					this.SendPropertyChanged("Numero_ordine");
					this.OnNumero_ordineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceImpiegato", DbType="Decimal(3,0) NOT NULL")]
		public decimal CodiceImpiegato
		{
			get
			{
				return this._CodiceImpiegato;
			}
			set
			{
				if ((this._CodiceImpiegato != value))
				{
					if (this._VENDITA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodiceImpiegatoChanging(value);
					this.SendPropertyChanging();
					this._CodiceImpiegato = value;
					this.SendPropertyChanged("CodiceImpiegato");
					this.OnCodiceImpiegatoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceVendita", DbType="Decimal(5,0) NOT NULL")]
		public decimal CodiceVendita
		{
			get
			{
				return this._CodiceVendita;
			}
			set
			{
				if ((this._CodiceVendita != value))
				{
					if (this._VENDITA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodiceVenditaChanging(value);
					this.SendPropertyChanging();
					this._CodiceVendita = value;
					this.SendPropertyChanged("CodiceVendita");
					this.OnCodiceVenditaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantità", DbType="Decimal(3,0) NOT NULL")]
		public decimal Quantità
		{
			get
			{
				return this._Quantità;
			}
			set
			{
				if ((this._Quantità != value))
				{
					this.OnQuantitàChanging(value);
					this.SendPropertyChanging();
					this._Quantità = value;
					this.SendPropertyChanged("Quantità");
					this.OnQuantitàChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Prezzo unitario]", Storage="_Prezzo_unitario", DbType="Decimal(5,0) NOT NULL")]
		public decimal Prezzo_unitario
		{
			get
			{
				return this._Prezzo_unitario;
			}
			set
			{
				if ((this._Prezzo_unitario != value))
				{
					this.OnPrezzo_unitarioChanging(value);
					this.SendPropertyChanging();
					this._Prezzo_unitario = value;
					this.SendPropertyChanged("Prezzo_unitario");
					this.OnPrezzo_unitarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VENDITA_DETTAGLIO_ORDINE", Storage="_VENDITA", ThisKey="CodiceImpiegato,CodiceVendita", OtherKey="CodiceImpiegato,CodiceVendita", IsForeignKey=true)]
		public VENDITA VENDITA
		{
			get
			{
				return this._VENDITA.Entity;
			}
			set
			{
				VENDITA previousValue = this._VENDITA.Entity;
				if (((previousValue != value) 
							|| (this._VENDITA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VENDITA.Entity = null;
						previousValue.DETTAGLIO_ORDINEs.Remove(this);
					}
					this._VENDITA.Entity = value;
					if ((value != null))
					{
						value.DETTAGLIO_ORDINEs.Add(this);
						this._CodiceImpiegato = value.CodiceImpiegato;
						this._CodiceVendita = value.CodiceVendita;
					}
					else
					{
						this._CodiceImpiegato = default(decimal);
						this._CodiceVendita = default(decimal);
					}
					this.SendPropertyChanged("VENDITA");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RICAMBIO_DETTAGLIO_ORDINE", Storage="_RICAMBIO", ThisKey="CodiceRicambio", OtherKey="CodiceRicambio", IsForeignKey=true)]
		public RICAMBIO RICAMBIO
		{
			get
			{
				return this._RICAMBIO.Entity;
			}
			set
			{
				RICAMBIO previousValue = this._RICAMBIO.Entity;
				if (((previousValue != value) 
							|| (this._RICAMBIO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._RICAMBIO.Entity = null;
						previousValue.DETTAGLIO_ORDINEs.Remove(this);
					}
					this._RICAMBIO.Entity = value;
					if ((value != null))
					{
						value.DETTAGLIO_ORDINEs.Add(this);
						this._CodiceRicambio = value.CodiceRicambio;
					}
					else
					{
						this._CodiceRicambio = default(decimal);
					}
					this.SendPropertyChanged("RICAMBIO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DIPENDENTE")]
	public partial class DIPENDENTE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _CodiceImpiegato;
		
		private string _CF;
		
		private string _Nome;
		
		private string _Cognome;
		
		private System.Nullable<decimal> _Telefono;
		
		private string _Mail;
		
		private System.DateTime _Data_di_nascita;
		
		private char _Attivo;
		
		private EntitySet<CONTRATTO> _CONTRATTOs;
		
		private EntitySet<RIGENERAZIONE> _RIGENERAZIONEs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodiceImpiegatoChanging(decimal value);
    partial void OnCodiceImpiegatoChanged();
    partial void OnCFChanging(string value);
    partial void OnCFChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnCognomeChanging(string value);
    partial void OnCognomeChanged();
    partial void OnTelefonoChanging(System.Nullable<decimal> value);
    partial void OnTelefonoChanged();
    partial void OnMailChanging(string value);
    partial void OnMailChanged();
    partial void OnData_di_nascitaChanging(System.DateTime value);
    partial void OnData_di_nascitaChanged();
    partial void OnAttivoChanging(char value);
    partial void OnAttivoChanged();
    #endregion
		
		public DIPENDENTE()
		{
			this._CONTRATTOs = new EntitySet<CONTRATTO>(new Action<CONTRATTO>(this.attach_CONTRATTOs), new Action<CONTRATTO>(this.detach_CONTRATTOs));
			this._RIGENERAZIONEs = new EntitySet<RIGENERAZIONE>(new Action<RIGENERAZIONE>(this.attach_RIGENERAZIONEs), new Action<RIGENERAZIONE>(this.detach_RIGENERAZIONEs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceImpiegato", DbType="Decimal(3,0) NOT NULL", IsPrimaryKey=true)]
		public decimal CodiceImpiegato
		{
			get
			{
				return this._CodiceImpiegato;
			}
			set
			{
				if ((this._CodiceImpiegato != value))
				{
					this.OnCodiceImpiegatoChanging(value);
					this.SendPropertyChanging();
					this._CodiceImpiegato = value;
					this.SendPropertyChanged("CodiceImpiegato");
					this.OnCodiceImpiegatoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CF", DbType="Char(25) NOT NULL", CanBeNull=false)]
		public string CF
		{
			get
			{
				return this._CF;
			}
			set
			{
				if ((this._CF != value))
				{
					this.OnCFChanging(value);
					this.SendPropertyChanging();
					this._CF = value;
					this.SendPropertyChanged("CF");
					this.OnCFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cognome", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string Cognome
		{
			get
			{
				return this._Cognome;
			}
			set
			{
				if ((this._Cognome != value))
				{
					this.OnCognomeChanging(value);
					this.SendPropertyChanging();
					this._Cognome = value;
					this.SendPropertyChanged("Cognome");
					this.OnCognomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail", DbType="Char(30)")]
		public string Mail
		{
			get
			{
				return this._Mail;
			}
			set
			{
				if ((this._Mail != value))
				{
					this.OnMailChanging(value);
					this.SendPropertyChanging();
					this._Mail = value;
					this.SendPropertyChanged("Mail");
					this.OnMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Data di nascita]", Storage="_Data_di_nascita", DbType="Date NOT NULL")]
		public System.DateTime Data_di_nascita
		{
			get
			{
				return this._Data_di_nascita;
			}
			set
			{
				if ((this._Data_di_nascita != value))
				{
					this.OnData_di_nascitaChanging(value);
					this.SendPropertyChanging();
					this._Data_di_nascita = value;
					this.SendPropertyChanged("Data_di_nascita");
					this.OnData_di_nascitaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attivo", DbType="Char(1) NOT NULL")]
		public char Attivo
		{
			get
			{
				return this._Attivo;
			}
			set
			{
				if ((this._Attivo != value))
				{
					this.OnAttivoChanging(value);
					this.SendPropertyChanging();
					this._Attivo = value;
					this.SendPropertyChanged("Attivo");
					this.OnAttivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DIPENDENTE_CONTRATTO", Storage="_CONTRATTOs", ThisKey="CodiceImpiegato", OtherKey="CodiceImpiegato")]
		public EntitySet<CONTRATTO> CONTRATTOs
		{
			get
			{
				return this._CONTRATTOs;
			}
			set
			{
				this._CONTRATTOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DIPENDENTE_RIGENERAZIONE", Storage="_RIGENERAZIONEs", ThisKey="CodiceImpiegato", OtherKey="CodiceImpiegato")]
		public EntitySet<RIGENERAZIONE> RIGENERAZIONEs
		{
			get
			{
				return this._RIGENERAZIONEs;
			}
			set
			{
				this._RIGENERAZIONEs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CONTRATTOs(CONTRATTO entity)
		{
			this.SendPropertyChanging();
			entity.DIPENDENTE = this;
		}
		
		private void detach_CONTRATTOs(CONTRATTO entity)
		{
			this.SendPropertyChanging();
			entity.DIPENDENTE = null;
		}
		
		private void attach_RIGENERAZIONEs(RIGENERAZIONE entity)
		{
			this.SendPropertyChanging();
			entity.DIPENDENTE = this;
		}
		
		private void detach_RIGENERAZIONEs(RIGENERAZIONE entity)
		{
			this.SendPropertyChanging();
			entity.DIPENDENTE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[FATTURA DI ACQUISTO]")]
	public partial class FATTURA_DI_ACQUISTO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _CodiceFatturaA;
		
		private System.DateTime _Data_emissione;
		
		private decimal _Importo_netto;
		
		private decimal _IVA;
		
		private decimal _P_IVA;
		
		private EntitySet<composizione_acquisto> _composizione_acquistos;
		
		private EntityRef<FORNITORE> _FORNITORE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodiceFatturaAChanging(decimal value);
    partial void OnCodiceFatturaAChanged();
    partial void OnData_emissioneChanging(System.DateTime value);
    partial void OnData_emissioneChanged();
    partial void OnImporto_nettoChanging(decimal value);
    partial void OnImporto_nettoChanged();
    partial void OnIVAChanging(decimal value);
    partial void OnIVAChanged();
    partial void OnP_IVAChanging(decimal value);
    partial void OnP_IVAChanged();
    #endregion
		
		public FATTURA_DI_ACQUISTO()
		{
			this._composizione_acquistos = new EntitySet<composizione_acquisto>(new Action<composizione_acquisto>(this.attach_composizione_acquistos), new Action<composizione_acquisto>(this.detach_composizione_acquistos));
			this._FORNITORE = default(EntityRef<FORNITORE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceFatturaA", DbType="Decimal(6,0) NOT NULL", IsPrimaryKey=true)]
		public decimal CodiceFatturaA
		{
			get
			{
				return this._CodiceFatturaA;
			}
			set
			{
				if ((this._CodiceFatturaA != value))
				{
					this.OnCodiceFatturaAChanging(value);
					this.SendPropertyChanging();
					this._CodiceFatturaA = value;
					this.SendPropertyChanged("CodiceFatturaA");
					this.OnCodiceFatturaAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Data emissione]", Storage="_Data_emissione", DbType="Date NOT NULL")]
		public System.DateTime Data_emissione
		{
			get
			{
				return this._Data_emissione;
			}
			set
			{
				if ((this._Data_emissione != value))
				{
					this.OnData_emissioneChanging(value);
					this.SendPropertyChanging();
					this._Data_emissione = value;
					this.SendPropertyChanged("Data_emissione");
					this.OnData_emissioneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Importo netto]", Storage="_Importo_netto", DbType="Decimal(6,0) NOT NULL")]
		public decimal Importo_netto
		{
			get
			{
				return this._Importo_netto;
			}
			set
			{
				if ((this._Importo_netto != value))
				{
					this.OnImporto_nettoChanging(value);
					this.SendPropertyChanging();
					this._Importo_netto = value;
					this.SendPropertyChanged("Importo_netto");
					this.OnImporto_nettoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IVA", DbType="Decimal(2,0) NOT NULL")]
		public decimal IVA
		{
			get
			{
				return this._IVA;
			}
			set
			{
				if ((this._IVA != value))
				{
					this.OnIVAChanging(value);
					this.SendPropertyChanging();
					this._IVA = value;
					this.SendPropertyChanged("IVA");
					this.OnIVAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[P.IVA]", Storage="_P_IVA", DbType="Decimal(10,0) NOT NULL")]
		public decimal P_IVA
		{
			get
			{
				return this._P_IVA;
			}
			set
			{
				if ((this._P_IVA != value))
				{
					this.OnP_IVAChanging(value);
					this.SendPropertyChanging();
					this._P_IVA = value;
					this.SendPropertyChanged("P_IVA");
					this.OnP_IVAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FATTURA_DI_ACQUISTO_composizione_acquisto", Storage="_composizione_acquistos", ThisKey="CodiceFatturaA", OtherKey="CodiceFatturaA")]
		public EntitySet<composizione_acquisto> composizione_acquistos
		{
			get
			{
				return this._composizione_acquistos;
			}
			set
			{
				this._composizione_acquistos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FORNITORE_FATTURA_DI_ACQUISTO", Storage="_FORNITORE", ThisKey="P_IVA", OtherKey="P_IVA", IsForeignKey=true)]
		public FORNITORE FORNITORE
		{
			get
			{
				return this._FORNITORE.Entity;
			}
			set
			{
				FORNITORE previousValue = this._FORNITORE.Entity;
				if (((previousValue != value) 
							|| (this._FORNITORE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._FORNITORE.Entity = null;
						previousValue.FATTURA_DI_ACQUISTOs.Remove(this);
					}
					this._FORNITORE.Entity = value;
					if ((value != null))
					{
						value.FATTURA_DI_ACQUISTOs.Add(this);
						this._P_IVA = value.P_IVA;
					}
					else
					{
						this._P_IVA = default(decimal);
					}
					this.SendPropertyChanged("FORNITORE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_composizione_acquistos(composizione_acquisto entity)
		{
			this.SendPropertyChanging();
			entity.FATTURA_DI_ACQUISTO = this;
		}
		
		private void detach_composizione_acquistos(composizione_acquisto entity)
		{
			this.SendPropertyChanging();
			entity.FATTURA_DI_ACQUISTO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[FATTURA DI VENDITA]")]
	public partial class FATTURA_DI_VENDITA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _CodiceFatturaV;
		
		private System.DateTime _Data_emissione;
		
		private decimal _Importo_netto;
		
		private decimal _IVA;
		
		private string _CF;
		
		private EntitySet<RIGENERAZIONE> _RIGENERAZIONEs;
		
		private EntityRef<CLIENTE> _CLIENTE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodiceFatturaVChanging(decimal value);
    partial void OnCodiceFatturaVChanged();
    partial void OnData_emissioneChanging(System.DateTime value);
    partial void OnData_emissioneChanged();
    partial void OnImporto_nettoChanging(decimal value);
    partial void OnImporto_nettoChanged();
    partial void OnIVAChanging(decimal value);
    partial void OnIVAChanged();
    partial void OnCFChanging(string value);
    partial void OnCFChanged();
    #endregion
		
		public FATTURA_DI_VENDITA()
		{
			this._RIGENERAZIONEs = new EntitySet<RIGENERAZIONE>(new Action<RIGENERAZIONE>(this.attach_RIGENERAZIONEs), new Action<RIGENERAZIONE>(this.detach_RIGENERAZIONEs));
			this._CLIENTE = default(EntityRef<CLIENTE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceFatturaV", DbType="Decimal(10,0) NOT NULL", IsPrimaryKey=true)]
		public decimal CodiceFatturaV
		{
			get
			{
				return this._CodiceFatturaV;
			}
			set
			{
				if ((this._CodiceFatturaV != value))
				{
					this.OnCodiceFatturaVChanging(value);
					this.SendPropertyChanging();
					this._CodiceFatturaV = value;
					this.SendPropertyChanged("CodiceFatturaV");
					this.OnCodiceFatturaVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Data emissione]", Storage="_Data_emissione", DbType="Date NOT NULL")]
		public System.DateTime Data_emissione
		{
			get
			{
				return this._Data_emissione;
			}
			set
			{
				if ((this._Data_emissione != value))
				{
					this.OnData_emissioneChanging(value);
					this.SendPropertyChanging();
					this._Data_emissione = value;
					this.SendPropertyChanged("Data_emissione");
					this.OnData_emissioneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Importo netto]", Storage="_Importo_netto", DbType="Decimal(10,0) NOT NULL")]
		public decimal Importo_netto
		{
			get
			{
				return this._Importo_netto;
			}
			set
			{
				if ((this._Importo_netto != value))
				{
					this.OnImporto_nettoChanging(value);
					this.SendPropertyChanging();
					this._Importo_netto = value;
					this.SendPropertyChanged("Importo_netto");
					this.OnImporto_nettoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IVA", DbType="Decimal(3,0) NOT NULL")]
		public decimal IVA
		{
			get
			{
				return this._IVA;
			}
			set
			{
				if ((this._IVA != value))
				{
					this.OnIVAChanging(value);
					this.SendPropertyChanging();
					this._IVA = value;
					this.SendPropertyChanged("IVA");
					this.OnIVAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CF", DbType="Char(25) NOT NULL", CanBeNull=false)]
		public string CF
		{
			get
			{
				return this._CF;
			}
			set
			{
				if ((this._CF != value))
				{
					if (this._CLIENTE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCFChanging(value);
					this.SendPropertyChanging();
					this._CF = value;
					this.SendPropertyChanged("CF");
					this.OnCFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FATTURA_DI_VENDITA_RIGENERAZIONE", Storage="_RIGENERAZIONEs", ThisKey="CodiceFatturaV", OtherKey="CodiceFatturaV")]
		public EntitySet<RIGENERAZIONE> RIGENERAZIONEs
		{
			get
			{
				return this._RIGENERAZIONEs;
			}
			set
			{
				this._RIGENERAZIONEs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLIENTE_FATTURA_DI_VENDITA", Storage="_CLIENTE", ThisKey="CF", OtherKey="CF", IsForeignKey=true)]
		public CLIENTE CLIENTE
		{
			get
			{
				return this._CLIENTE.Entity;
			}
			set
			{
				CLIENTE previousValue = this._CLIENTE.Entity;
				if (((previousValue != value) 
							|| (this._CLIENTE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CLIENTE.Entity = null;
						previousValue.FATTURA_DI_VENDITAs.Remove(this);
					}
					this._CLIENTE.Entity = value;
					if ((value != null))
					{
						value.FATTURA_DI_VENDITAs.Add(this);
						this._CF = value.CF;
					}
					else
					{
						this._CF = default(string);
					}
					this.SendPropertyChanged("CLIENTE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RIGENERAZIONEs(RIGENERAZIONE entity)
		{
			this.SendPropertyChanging();
			entity.FATTURA_DI_VENDITA = this;
		}
		
		private void detach_RIGENERAZIONEs(RIGENERAZIONE entity)
		{
			this.SendPropertyChanging();
			entity.FATTURA_DI_VENDITA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FORNITORE")]
	public partial class FORNITORE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _P_IVA;
		
		private string _Nome_azienda;
		
		private System.Nullable<decimal> _Telefono;
		
		private string _Mail;
		
		private string _Indirizzo;
		
		private EntitySet<FATTURA_DI_ACQUISTO> _FATTURA_DI_ACQUISTOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnP_IVAChanging(decimal value);
    partial void OnP_IVAChanged();
    partial void OnNome_aziendaChanging(string value);
    partial void OnNome_aziendaChanged();
    partial void OnTelefonoChanging(System.Nullable<decimal> value);
    partial void OnTelefonoChanged();
    partial void OnMailChanging(string value);
    partial void OnMailChanged();
    partial void OnIndirizzoChanging(string value);
    partial void OnIndirizzoChanged();
    #endregion
		
		public FORNITORE()
		{
			this._FATTURA_DI_ACQUISTOs = new EntitySet<FATTURA_DI_ACQUISTO>(new Action<FATTURA_DI_ACQUISTO>(this.attach_FATTURA_DI_ACQUISTOs), new Action<FATTURA_DI_ACQUISTO>(this.detach_FATTURA_DI_ACQUISTOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[P.IVA]", Storage="_P_IVA", DbType="Decimal(10,0) NOT NULL", IsPrimaryKey=true)]
		public decimal P_IVA
		{
			get
			{
				return this._P_IVA;
			}
			set
			{
				if ((this._P_IVA != value))
				{
					this.OnP_IVAChanging(value);
					this.SendPropertyChanging();
					this._P_IVA = value;
					this.SendPropertyChanged("P_IVA");
					this.OnP_IVAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nome azienda]", Storage="_Nome_azienda", DbType="Char(30) NOT NULL", CanBeNull=false)]
		public string Nome_azienda
		{
			get
			{
				return this._Nome_azienda;
			}
			set
			{
				if ((this._Nome_azienda != value))
				{
					this.OnNome_aziendaChanging(value);
					this.SendPropertyChanging();
					this._Nome_azienda = value;
					this.SendPropertyChanged("Nome_azienda");
					this.OnNome_aziendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail", DbType="Char(30)")]
		public string Mail
		{
			get
			{
				return this._Mail;
			}
			set
			{
				if ((this._Mail != value))
				{
					this.OnMailChanging(value);
					this.SendPropertyChanging();
					this._Mail = value;
					this.SendPropertyChanged("Mail");
					this.OnMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Indirizzo", DbType="Char(30) NOT NULL", CanBeNull=false)]
		public string Indirizzo
		{
			get
			{
				return this._Indirizzo;
			}
			set
			{
				if ((this._Indirizzo != value))
				{
					this.OnIndirizzoChanging(value);
					this.SendPropertyChanging();
					this._Indirizzo = value;
					this.SendPropertyChanged("Indirizzo");
					this.OnIndirizzoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FORNITORE_FATTURA_DI_ACQUISTO", Storage="_FATTURA_DI_ACQUISTOs", ThisKey="P_IVA", OtherKey="P_IVA")]
		public EntitySet<FATTURA_DI_ACQUISTO> FATTURA_DI_ACQUISTOs
		{
			get
			{
				return this._FATTURA_DI_ACQUISTOs;
			}
			set
			{
				this._FATTURA_DI_ACQUISTOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_FATTURA_DI_ACQUISTOs(FATTURA_DI_ACQUISTO entity)
		{
			this.SendPropertyChanging();
			entity.FORNITORE = this;
		}
		
		private void detach_FATTURA_DI_ACQUISTOs(FATTURA_DI_ACQUISTO entity)
		{
			this.SendPropertyChanging();
			entity.FORNITORE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAGAZZINO")]
	public partial class MAGAZZINO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _CodiceMagazzino;
		
		private string _Indirizzo;
		
		private decimal _Corsia;
		
		private EntitySet<RICAMBIO> _RICAMBIOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodiceMagazzinoChanging(decimal value);
    partial void OnCodiceMagazzinoChanged();
    partial void OnIndirizzoChanging(string value);
    partial void OnIndirizzoChanged();
    partial void OnCorsiaChanging(decimal value);
    partial void OnCorsiaChanged();
    #endregion
		
		public MAGAZZINO()
		{
			this._RICAMBIOs = new EntitySet<RICAMBIO>(new Action<RICAMBIO>(this.attach_RICAMBIOs), new Action<RICAMBIO>(this.detach_RICAMBIOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceMagazzino", DbType="Decimal(3,0) NOT NULL", IsPrimaryKey=true)]
		public decimal CodiceMagazzino
		{
			get
			{
				return this._CodiceMagazzino;
			}
			set
			{
				if ((this._CodiceMagazzino != value))
				{
					this.OnCodiceMagazzinoChanging(value);
					this.SendPropertyChanging();
					this._CodiceMagazzino = value;
					this.SendPropertyChanged("CodiceMagazzino");
					this.OnCodiceMagazzinoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Indirizzo", DbType="Char(30)")]
		public string Indirizzo
		{
			get
			{
				return this._Indirizzo;
			}
			set
			{
				if ((this._Indirizzo != value))
				{
					this.OnIndirizzoChanging(value);
					this.SendPropertyChanging();
					this._Indirizzo = value;
					this.SendPropertyChanged("Indirizzo");
					this.OnIndirizzoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Corsia", DbType="Decimal(3,0) NOT NULL")]
		public decimal Corsia
		{
			get
			{
				return this._Corsia;
			}
			set
			{
				if ((this._Corsia != value))
				{
					this.OnCorsiaChanging(value);
					this.SendPropertyChanging();
					this._Corsia = value;
					this.SendPropertyChanged("Corsia");
					this.OnCorsiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAGAZZINO_RICAMBIO", Storage="_RICAMBIOs", ThisKey="CodiceMagazzino", OtherKey="CodiceMagazzino")]
		public EntitySet<RICAMBIO> RICAMBIOs
		{
			get
			{
				return this._RICAMBIOs;
			}
			set
			{
				this._RICAMBIOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RICAMBIOs(RICAMBIO entity)
		{
			this.SendPropertyChanging();
			entity.MAGAZZINO = this;
		}
		
		private void detach_RICAMBIOs(RICAMBIO entity)
		{
			this.SendPropertyChanging();
			entity.MAGAZZINO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MOTO")]
	public partial class MOTO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Numero_telaio;
		
		private string _Marca;
		
		private string _Modello;
		
		private decimal _Cilindrata;
		
		private string _CF;
		
		private EntityRef<CLIENTE> _CLIENTE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNumero_telaioChanging(decimal value);
    partial void OnNumero_telaioChanged();
    partial void OnMarcaChanging(string value);
    partial void OnMarcaChanged();
    partial void OnModelloChanging(string value);
    partial void OnModelloChanged();
    partial void OnCilindrataChanging(decimal value);
    partial void OnCilindrataChanged();
    partial void OnCFChanging(string value);
    partial void OnCFChanged();
    #endregion
		
		public MOTO()
		{
			this._CLIENTE = default(EntityRef<CLIENTE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Numero telaio]", Storage="_Numero_telaio", DbType="Decimal(10,0) NOT NULL", IsPrimaryKey=true)]
		public decimal Numero_telaio
		{
			get
			{
				return this._Numero_telaio;
			}
			set
			{
				if ((this._Numero_telaio != value))
				{
					this.OnNumero_telaioChanging(value);
					this.SendPropertyChanging();
					this._Numero_telaio = value;
					this.SendPropertyChanged("Numero_telaio");
					this.OnNumero_telaioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marca", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string Marca
		{
			get
			{
				return this._Marca;
			}
			set
			{
				if ((this._Marca != value))
				{
					this.OnMarcaChanging(value);
					this.SendPropertyChanging();
					this._Marca = value;
					this.SendPropertyChanged("Marca");
					this.OnMarcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modello", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string Modello
		{
			get
			{
				return this._Modello;
			}
			set
			{
				if ((this._Modello != value))
				{
					this.OnModelloChanging(value);
					this.SendPropertyChanging();
					this._Modello = value;
					this.SendPropertyChanged("Modello");
					this.OnModelloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cilindrata", DbType="Decimal(4,0) NOT NULL")]
		public decimal Cilindrata
		{
			get
			{
				return this._Cilindrata;
			}
			set
			{
				if ((this._Cilindrata != value))
				{
					this.OnCilindrataChanging(value);
					this.SendPropertyChanging();
					this._Cilindrata = value;
					this.SendPropertyChanged("Cilindrata");
					this.OnCilindrataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CF", DbType="Char(25) NOT NULL", CanBeNull=false)]
		public string CF
		{
			get
			{
				return this._CF;
			}
			set
			{
				if ((this._CF != value))
				{
					if (this._CLIENTE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCFChanging(value);
					this.SendPropertyChanging();
					this._CF = value;
					this.SendPropertyChanged("CF");
					this.OnCFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLIENTE_MOTO", Storage="_CLIENTE", ThisKey="CF", OtherKey="CF", IsForeignKey=true)]
		public CLIENTE CLIENTE
		{
			get
			{
				return this._CLIENTE.Entity;
			}
			set
			{
				CLIENTE previousValue = this._CLIENTE.Entity;
				if (((previousValue != value) 
							|| (this._CLIENTE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CLIENTE.Entity = null;
						previousValue.MOTOs.Remove(this);
					}
					this._CLIENTE.Entity = value;
					if ((value != null))
					{
						value.MOTOs.Add(this);
						this._CF = value.CF;
					}
					else
					{
						this._CF = default(string);
					}
					this.SendPropertyChanged("CLIENTE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RICAMBIO")]
	public partial class RICAMBIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _CodiceRicambio;
		
		private string _Marca;
		
		private string _Categoria;
		
		private decimal _Quantità_scorta;
		
		private string _Descrizione;
		
		private decimal _CodiceMagazzino;
		
		private EntitySet<composizione_acquisto> _composizione_acquistos;
		
		private EntitySet<DETTAGLIO_ORDINE> _DETTAGLIO_ORDINEs;
		
		private EntityRef<MAGAZZINO> _MAGAZZINO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodiceRicambioChanging(decimal value);
    partial void OnCodiceRicambioChanged();
    partial void OnMarcaChanging(string value);
    partial void OnMarcaChanged();
    partial void OnCategoriaChanging(string value);
    partial void OnCategoriaChanged();
    partial void OnQuantità_scortaChanging(decimal value);
    partial void OnQuantità_scortaChanged();
    partial void OnDescrizioneChanging(string value);
    partial void OnDescrizioneChanged();
    partial void OnCodiceMagazzinoChanging(decimal value);
    partial void OnCodiceMagazzinoChanged();
    #endregion
		
		public RICAMBIO()
		{
			this._composizione_acquistos = new EntitySet<composizione_acquisto>(new Action<composizione_acquisto>(this.attach_composizione_acquistos), new Action<composizione_acquisto>(this.detach_composizione_acquistos));
			this._DETTAGLIO_ORDINEs = new EntitySet<DETTAGLIO_ORDINE>(new Action<DETTAGLIO_ORDINE>(this.attach_DETTAGLIO_ORDINEs), new Action<DETTAGLIO_ORDINE>(this.detach_DETTAGLIO_ORDINEs));
			this._MAGAZZINO = default(EntityRef<MAGAZZINO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceRicambio", DbType="Decimal(6,0) NOT NULL", IsPrimaryKey=true)]
		public decimal CodiceRicambio
		{
			get
			{
				return this._CodiceRicambio;
			}
			set
			{
				if ((this._CodiceRicambio != value))
				{
					this.OnCodiceRicambioChanging(value);
					this.SendPropertyChanging();
					this._CodiceRicambio = value;
					this.SendPropertyChanged("CodiceRicambio");
					this.OnCodiceRicambioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marca", DbType="Char(30) NOT NULL", CanBeNull=false)]
		public string Marca
		{
			get
			{
				return this._Marca;
			}
			set
			{
				if ((this._Marca != value))
				{
					this.OnMarcaChanging(value);
					this.SendPropertyChanging();
					this._Marca = value;
					this.SendPropertyChanged("Marca");
					this.OnMarcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="Char(30) NOT NULL", CanBeNull=false)]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this.OnCategoriaChanging(value);
					this.SendPropertyChanging();
					this._Categoria = value;
					this.SendPropertyChanged("Categoria");
					this.OnCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Quantità scorta]", Storage="_Quantità_scorta", DbType="Decimal(4,0) NOT NULL")]
		public decimal Quantità_scorta
		{
			get
			{
				return this._Quantità_scorta;
			}
			set
			{
				if ((this._Quantità_scorta != value))
				{
					this.OnQuantità_scortaChanging(value);
					this.SendPropertyChanging();
					this._Quantità_scorta = value;
					this.SendPropertyChanged("Quantità_scorta");
					this.OnQuantità_scortaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descrizione", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string Descrizione
		{
			get
			{
				return this._Descrizione;
			}
			set
			{
				if ((this._Descrizione != value))
				{
					this.OnDescrizioneChanging(value);
					this.SendPropertyChanging();
					this._Descrizione = value;
					this.SendPropertyChanged("Descrizione");
					this.OnDescrizioneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceMagazzino", DbType="Decimal(3,0) NOT NULL")]
		public decimal CodiceMagazzino
		{
			get
			{
				return this._CodiceMagazzino;
			}
			set
			{
				if ((this._CodiceMagazzino != value))
				{
					if (this._MAGAZZINO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodiceMagazzinoChanging(value);
					this.SendPropertyChanging();
					this._CodiceMagazzino = value;
					this.SendPropertyChanged("CodiceMagazzino");
					this.OnCodiceMagazzinoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RICAMBIO_composizione_acquisto", Storage="_composizione_acquistos", ThisKey="CodiceRicambio", OtherKey="CodiceRicambio")]
		public EntitySet<composizione_acquisto> composizione_acquistos
		{
			get
			{
				return this._composizione_acquistos;
			}
			set
			{
				this._composizione_acquistos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RICAMBIO_DETTAGLIO_ORDINE", Storage="_DETTAGLIO_ORDINEs", ThisKey="CodiceRicambio", OtherKey="CodiceRicambio")]
		public EntitySet<DETTAGLIO_ORDINE> DETTAGLIO_ORDINEs
		{
			get
			{
				return this._DETTAGLIO_ORDINEs;
			}
			set
			{
				this._DETTAGLIO_ORDINEs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAGAZZINO_RICAMBIO", Storage="_MAGAZZINO", ThisKey="CodiceMagazzino", OtherKey="CodiceMagazzino", IsForeignKey=true)]
		public MAGAZZINO MAGAZZINO
		{
			get
			{
				return this._MAGAZZINO.Entity;
			}
			set
			{
				MAGAZZINO previousValue = this._MAGAZZINO.Entity;
				if (((previousValue != value) 
							|| (this._MAGAZZINO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MAGAZZINO.Entity = null;
						previousValue.RICAMBIOs.Remove(this);
					}
					this._MAGAZZINO.Entity = value;
					if ((value != null))
					{
						value.RICAMBIOs.Add(this);
						this._CodiceMagazzino = value.CodiceMagazzino;
					}
					else
					{
						this._CodiceMagazzino = default(decimal);
					}
					this.SendPropertyChanged("MAGAZZINO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_composizione_acquistos(composizione_acquisto entity)
		{
			this.SendPropertyChanging();
			entity.RICAMBIO = this;
		}
		
		private void detach_composizione_acquistos(composizione_acquisto entity)
		{
			this.SendPropertyChanging();
			entity.RICAMBIO = null;
		}
		
		private void attach_DETTAGLIO_ORDINEs(DETTAGLIO_ORDINE entity)
		{
			this.SendPropertyChanging();
			entity.RICAMBIO = this;
		}
		
		private void detach_DETTAGLIO_ORDINEs(DETTAGLIO_ORDINE entity)
		{
			this.SendPropertyChanging();
			entity.RICAMBIO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RIGENERAZIONE")]
	public partial class RIGENERAZIONE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _CodiceImpiegato;
		
		private decimal _CodiceRigenerazione;
		
		private System.DateTime _Data_rilascio;
		
		private string _Descrizione;
		
		private decimal _CodiceFatturaV;
		
		private EntityRef<DIPENDENTE> _DIPENDENTE;
		
		private EntityRef<FATTURA_DI_VENDITA> _FATTURA_DI_VENDITA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodiceImpiegatoChanging(decimal value);
    partial void OnCodiceImpiegatoChanged();
    partial void OnCodiceRigenerazioneChanging(decimal value);
    partial void OnCodiceRigenerazioneChanged();
    partial void OnData_rilascioChanging(System.DateTime value);
    partial void OnData_rilascioChanged();
    partial void OnDescrizioneChanging(string value);
    partial void OnDescrizioneChanged();
    partial void OnCodiceFatturaVChanging(decimal value);
    partial void OnCodiceFatturaVChanged();
    #endregion
		
		public RIGENERAZIONE()
		{
			this._DIPENDENTE = default(EntityRef<DIPENDENTE>);
			this._FATTURA_DI_VENDITA = default(EntityRef<FATTURA_DI_VENDITA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceImpiegato", DbType="Decimal(3,0) NOT NULL", IsPrimaryKey=true)]
		public decimal CodiceImpiegato
		{
			get
			{
				return this._CodiceImpiegato;
			}
			set
			{
				if ((this._CodiceImpiegato != value))
				{
					if (this._DIPENDENTE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodiceImpiegatoChanging(value);
					this.SendPropertyChanging();
					this._CodiceImpiegato = value;
					this.SendPropertyChanged("CodiceImpiegato");
					this.OnCodiceImpiegatoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceRigenerazione", DbType="Decimal(5,0) NOT NULL", IsPrimaryKey=true)]
		public decimal CodiceRigenerazione
		{
			get
			{
				return this._CodiceRigenerazione;
			}
			set
			{
				if ((this._CodiceRigenerazione != value))
				{
					this.OnCodiceRigenerazioneChanging(value);
					this.SendPropertyChanging();
					this._CodiceRigenerazione = value;
					this.SendPropertyChanged("CodiceRigenerazione");
					this.OnCodiceRigenerazioneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Data rilascio]", Storage="_Data_rilascio", DbType="Date NOT NULL")]
		public System.DateTime Data_rilascio
		{
			get
			{
				return this._Data_rilascio;
			}
			set
			{
				if ((this._Data_rilascio != value))
				{
					this.OnData_rilascioChanging(value);
					this.SendPropertyChanging();
					this._Data_rilascio = value;
					this.SendPropertyChanged("Data_rilascio");
					this.OnData_rilascioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descrizione", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string Descrizione
		{
			get
			{
				return this._Descrizione;
			}
			set
			{
				if ((this._Descrizione != value))
				{
					this.OnDescrizioneChanging(value);
					this.SendPropertyChanging();
					this._Descrizione = value;
					this.SendPropertyChanged("Descrizione");
					this.OnDescrizioneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceFatturaV", DbType="Decimal(10,0) NOT NULL")]
		public decimal CodiceFatturaV
		{
			get
			{
				return this._CodiceFatturaV;
			}
			set
			{
				if ((this._CodiceFatturaV != value))
				{
					if (this._FATTURA_DI_VENDITA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodiceFatturaVChanging(value);
					this.SendPropertyChanging();
					this._CodiceFatturaV = value;
					this.SendPropertyChanged("CodiceFatturaV");
					this.OnCodiceFatturaVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DIPENDENTE_RIGENERAZIONE", Storage="_DIPENDENTE", ThisKey="CodiceImpiegato", OtherKey="CodiceImpiegato", IsForeignKey=true)]
		public DIPENDENTE DIPENDENTE
		{
			get
			{
				return this._DIPENDENTE.Entity;
			}
			set
			{
				DIPENDENTE previousValue = this._DIPENDENTE.Entity;
				if (((previousValue != value) 
							|| (this._DIPENDENTE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DIPENDENTE.Entity = null;
						previousValue.RIGENERAZIONEs.Remove(this);
					}
					this._DIPENDENTE.Entity = value;
					if ((value != null))
					{
						value.RIGENERAZIONEs.Add(this);
						this._CodiceImpiegato = value.CodiceImpiegato;
					}
					else
					{
						this._CodiceImpiegato = default(decimal);
					}
					this.SendPropertyChanged("DIPENDENTE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FATTURA_DI_VENDITA_RIGENERAZIONE", Storage="_FATTURA_DI_VENDITA", ThisKey="CodiceFatturaV", OtherKey="CodiceFatturaV", IsForeignKey=true)]
		public FATTURA_DI_VENDITA FATTURA_DI_VENDITA
		{
			get
			{
				return this._FATTURA_DI_VENDITA.Entity;
			}
			set
			{
				FATTURA_DI_VENDITA previousValue = this._FATTURA_DI_VENDITA.Entity;
				if (((previousValue != value) 
							|| (this._FATTURA_DI_VENDITA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._FATTURA_DI_VENDITA.Entity = null;
						previousValue.RIGENERAZIONEs.Remove(this);
					}
					this._FATTURA_DI_VENDITA.Entity = value;
					if ((value != null))
					{
						value.RIGENERAZIONEs.Add(this);
						this._CodiceFatturaV = value.CodiceFatturaV;
					}
					else
					{
						this._CodiceFatturaV = default(decimal);
					}
					this.SendPropertyChanged("FATTURA_DI_VENDITA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TITOLARE")]
	public partial class TITOLARE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Codicetitolare;
		
		private string _CF;
		
		private string _Nome;
		
		private string _Cognome;
		
		private System.Nullable<decimal> _Telefono;
		
		private string _Mail;
		
		private System.DateTime _Data_di_nascita;
		
		private EntitySet<CONTRATTO> _CONTRATTOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodicetitolareChanging(decimal value);
    partial void OnCodicetitolareChanged();
    partial void OnCFChanging(string value);
    partial void OnCFChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnCognomeChanging(string value);
    partial void OnCognomeChanged();
    partial void OnTelefonoChanging(System.Nullable<decimal> value);
    partial void OnTelefonoChanged();
    partial void OnMailChanging(string value);
    partial void OnMailChanged();
    partial void OnData_di_nascitaChanging(System.DateTime value);
    partial void OnData_di_nascitaChanged();
    #endregion
		
		public TITOLARE()
		{
			this._CONTRATTOs = new EntitySet<CONTRATTO>(new Action<CONTRATTO>(this.attach_CONTRATTOs), new Action<CONTRATTO>(this.detach_CONTRATTOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codicetitolare", DbType="Decimal(2,0) NOT NULL", IsPrimaryKey=true)]
		public decimal Codicetitolare
		{
			get
			{
				return this._Codicetitolare;
			}
			set
			{
				if ((this._Codicetitolare != value))
				{
					this.OnCodicetitolareChanging(value);
					this.SendPropertyChanging();
					this._Codicetitolare = value;
					this.SendPropertyChanged("Codicetitolare");
					this.OnCodicetitolareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CF", DbType="Char(25) NOT NULL", CanBeNull=false)]
		public string CF
		{
			get
			{
				return this._CF;
			}
			set
			{
				if ((this._CF != value))
				{
					this.OnCFChanging(value);
					this.SendPropertyChanging();
					this._CF = value;
					this.SendPropertyChanged("CF");
					this.OnCFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cognome", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string Cognome
		{
			get
			{
				return this._Cognome;
			}
			set
			{
				if ((this._Cognome != value))
				{
					this.OnCognomeChanging(value);
					this.SendPropertyChanging();
					this._Cognome = value;
					this.SendPropertyChanged("Cognome");
					this.OnCognomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail", DbType="Char(30)")]
		public string Mail
		{
			get
			{
				return this._Mail;
			}
			set
			{
				if ((this._Mail != value))
				{
					this.OnMailChanging(value);
					this.SendPropertyChanging();
					this._Mail = value;
					this.SendPropertyChanged("Mail");
					this.OnMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Data di nascita]", Storage="_Data_di_nascita", DbType="Date NOT NULL")]
		public System.DateTime Data_di_nascita
		{
			get
			{
				return this._Data_di_nascita;
			}
			set
			{
				if ((this._Data_di_nascita != value))
				{
					this.OnData_di_nascitaChanging(value);
					this.SendPropertyChanging();
					this._Data_di_nascita = value;
					this.SendPropertyChanged("Data_di_nascita");
					this.OnData_di_nascitaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TITOLARE_CONTRATTO", Storage="_CONTRATTOs", ThisKey="Codicetitolare", OtherKey="Codicetitolare")]
		public EntitySet<CONTRATTO> CONTRATTOs
		{
			get
			{
				return this._CONTRATTOs;
			}
			set
			{
				this._CONTRATTOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CONTRATTOs(CONTRATTO entity)
		{
			this.SendPropertyChanging();
			entity.TITOLARE = this;
		}
		
		private void detach_CONTRATTOs(CONTRATTO entity)
		{
			this.SendPropertyChanging();
			entity.TITOLARE = null;
		}
	}
}
#pragma warning restore 1591
